<a href="https://colab.research.google.com/github/ndsoi/MachineLearning/blob/main/KNN%E9%82%BB%E8%BF%91.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

调用模型

In [44]:
# 导入必要的库
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

# 加载鸢尾花数据集
iris = datasets.load_iris()
X = iris.data
y = iris.target

# 划分数据集为训练集和测试集
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 数据标准化（可选步骤，但通常对KNN有帮助）
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# 创建KNN分类器实例（这里我们选择K=3作为示例）
knn = KNeighborsClassifier(n_neighbors=40)

# 训练模型
knn.fit(X_train, y_train)

# 使用模型进行预测
y_pred = knn.predict(X_test)

# 打印分类报告和混淆矩阵
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.90      1.00      0.95         9
           2       1.00      0.91      0.95        11

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30

[[10  0  0]
 [ 0  9  0]
 [ 0  1 10]]


自编写过程，好处是可以定义不同的距离计算方式

In [47]:
## KNN
## 自定义欧式距离vsKNN模型（也是欧式距离）
import numpy as np
# 加载鸢尾花数据集
iris = datasets.load_iris()
X = iris.data
y = iris.target

# 划分数据集为训练集和测试集
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 数据标准化（可选步骤，但通常对KNN有帮助）
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

def distance(x,xi):
  n = xi.shape[0]
  sum = 0
  for i in range(n):
    sum += np.power((x[i]-xi[i]),2)
  return np.sqrt(sum)

def myKnn(X_train,y_train,x_test,k):
  allD = []
  for i in range(len(X_train)):
    tmp = distance(X_train[i],x_test)
    allD.append([tmp,i])

  allD.sort(key=lambda x:x[0])

  allDk = allD[:k]
  res = []
  for i in allDk:
    res.append(y_train[i[1]])
  return max(res,key=res.count)

def myKNN(X_train,y_train,X_test,k):
  pred = []
  n = X_test.shape[0]
  for i in range(n):
    pred.append(myKnn(X_train,y_train,X_test[i],k))
  return pred

pred = myKNN(X_train,y_train,X_test,40)
acc = 0
for i in range(len(pred)):
  if pred[i]==y_test[i]:
    acc += 1
acc /= len(pred)
print(f'分类精度{acc}')


分类精度0.9666666666666667
